DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o.
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/lmb/public> {
    ?s ?p ?o.
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o.
  }
}
