PREFIX rpioHttp: <http://redpencil.data.gift/vocabularies/http/>
PREFIX http: <http://www.w3.org/2011/http#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/harvesting> {
  <http://data.lblod.info/request-headers/accept/text/html> a http:RequestHeader;
                                                              http:fieldValue "text/html";
                                                              http:fieldName "Accept";
                                                              http:hdrName <http://www.w3.org/2011/http-headers#accept>.  
  }
}
    