PREFIX cleanup: <http://mu.semte.ch/vocabularies/ext/cleanup/>
DELETE {
 GRAPH ?g {
    <http://localhost/cleanup-job-2> cleanup:randomQuery ?query
    }
 }
 WHERE {
      GRAPH ?g {
    <http://localhost/cleanup-job-2> cleanup:randomQuery ?query
    }
};
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/cleanup-jobs> {
    <http://localhost/cleanup-job-2> cleanup:randomQuery """
    INSERT  {
      GRAPH <http://mu.semte.ch/graphs/harvesting> {
      ?resource adms:status <http://redpencil.data.gift/id/concept/JobStatus/failed>;
      }
      }
      DELETE  {
      GRAPH <http://mu.semte.ch/graphs/harvesting> {
      ?resource adms:status <http://redpencil.data.gift/id/concept/JobStatus/busy>;
      }
    }
    WHERE {
    GRAPH <http://mu.semte.ch/graphs/harvesting> {
      ?resource a <http://redpencil.data.gift/vocabularies/tasks/Task> ;
        adms:status <http://redpencil.data.gift/id/concept/JobStatus/busy>;
        <http://purl.org/dc/terms/modified> ?modified.
        BIND(NOW() - xsd:dayTimeDuration(\"PT36H\") AS ?hoursAgo)
     FILTER(?modified <= ?hoursAgo)
    }
    }
    """.
    }
 }