INSERT DATA
{
  GRAPH <http://mu.semte.ch/graphs/harvesting> 
  {
 	<http://redpencil.data.gift/id/scheduled-job/2dc62b6a-72c6-4331-8cf4-6d0b2a91cf39> a <http://vocab.deri.ie/cogs#ScheduledJob>;
	<http://purl.org/dc/terms/created> "2025-02-24T09:06:01.294Z";
	<http://purl.org/dc/terms/modified> "2025-02-24T09:06:01.294Z";
	<http://redpencil.data.gift/vocabularies/tasks/operation> <http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/deltaDumpFileCreation/besluiten>;
	<http://redpencil.data.gift/vocabularies/tasks/schedule> <http://redpencil.data.gift/id/cron-schedule/51ed491f-a188-434a-b946-6184ccedde89>;
	<http://mu.semte.ch/vocabularies/core/uuid> "2dc62b6a-72c6-4331-8cf4-6d0b2a91cf39";
	<http://purl.org/dc/terms/creator> <http://lblod.data.gift/services/graph-dump-publisher>;
	<http://purl.org/dc/terms/title> "Dump files".


	<http://redpencil.data.gift/id/cron-schedule/51ed491f-a188-434a-b946-6184ccedde89> a <http://redpencil.data.gift/vocabularies/tasks/CronSchedule>;
	<http://schema.org/repeatFrequency>  "0 23 * * *";
	<http://mu.semte.ch/vocabularies/core/uuid> "51ed491f-a188-434a-b946-6184ccedde89".
	
	
	
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://redpencil.data.gift/vocabularies/tasks/ScheduledTask> .
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> <http://mu.semte.ch/vocabularies/core/uuid> "4c987d7b-557d-4089-830e-d75876d775fb" .
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> <http://purl.org/dc/terms/created> "2024-01-26T15:06:01.265Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> <http://purl.org/dc/terms/modified> "2024-01-26T15:06:01.265Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> 	<http://redpencil.data.gift/vocabularies/tasks/operation> <http://redpencil.data.gift/id/jobs/concept/TaskOperation/deltas/deltaDumpFileCreation> .
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> <http://redpencil.data.gift/vocabularies/tasks/index> "0"^^<http://www.w3.org/2001/XMLSchema#integer>.
<http://redpencil.data.gift/id/scheduled-task/4c987d7b-557d-4089-830e-d75876d775fb> <http://purl.org/dc/terms/isPartOf> <http://redpencil.data.gift/id/scheduled-job/2dc62b6a-72c6-4331-8cf4-6d0b2a91cf39> .

  }
}