PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s prov:wasDerivedFrom ?o.
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s prov:wasDerivedFrom ?source.
  }
}
WHERE {
    GRAPH <http://mu.semte.ch/graphs/public> {
        ?s prov:wasDerivedFrom ?o.
        ?o owl:sameAs ?source.
    }
}