DELETE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
}  INSERT {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?stringified .
  }
} WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
    FILTER(datatype(?o) = "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString")
    BIND(STR(?o) AS ?stringified)
  }
}
