PREFIX dct: <http://purl.org/dc/terms/>
PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>

# sprintf workaround
INSERT DATA {
  GRAPH <http://graph.mu.semte.ch/workarounds/d930a21d-750e-427b-8b9e-bdc226e78bde> {
    <http://a/subject/d930a21d-750e-427b-8b9e-bdc226e78bde> dct:publisher <http://data.lblod.info/services/loket-producer>;
      a nfo:FileDataObject.
  }
}

;

DELETE {
  GRAPH ?g {
    ?s dct:publisher <http://data.lblod.info/services/loket-producer>.
  }
}
INSERT {
  GRAPH ?g {
    ?s dct:publisher <http://data.lblod.info/services/delta-production-json-diff-file-manager-besluiten>.
  }
}
WHERE {
  GRAPH ?g {
    ?s a nfo:FileDataObject ;
      dct:publisher <http://data.lblod.info/services/loket-producer> .
  }
}

;

# sprintf workaround
DELETE DATA {
  GRAPH <http://graph.mu.semte.ch/workarounds/d930a21d-750e-427b-8b9e-bdc226e78bde> {
    <http://a/subject/d930a21d-750e-427b-8b9e-bdc226e78bde> dct:publisher <http://data.lblod.info/services/delta-production-json-diff-file-manager-besluiten>;
      a nfo:FileDataObject.
  }
}